services:
  leadforge-api:
    image: ghcr.io/muhammedadebiyi/leadforge/api:latest
    container_name: leadforge-api
    restart: unless-stopped
    env_file: .env.production
    ports:
      - "4000:4000"
    networks:
      - leadforge-net

  leadforge-email-worker:
    image: ghcr.io/muhammedadebiyi/leadforge/email-worker:latest
    container_name: leadforge-email-worker
    restart: unless-stopped
    env_file: .env.production
    networks:
      - leadforge-net

  leadforge-telegram-worker:
    image: ghcr.io/muhammedadebiyi/leadforge/telegram-worker:latest
    container_name: leadforge-telegram-worker
    restart: unless-stopped
    env_file: .env.production
    networks:
      - leadforge-net

  leadforge-export-worker:
    image: ghcr.io/muhammedadebiyi/leadforge/export-worker:latest
    container_name: leadforge-export-worker
    restart: unless-stopped
    env_file: .env.production
    networks:
      - leadforge-net

  leadforge-website-worker:
    image: ghcr.io/muhammedadebiyi/leadforge/website-worker:latest
    container_name: leadforge-website-worker
    restart: unless-stopped
    env_file: .env.production
    networks:
      - leadforge-net

  leadforge-search-worker:
    image: ghcr.io/muhammedadebiyi/leadforge/search-worker:latest
    container_name: leadforge-search-worker
    restart: unless-stopped
    env_file: .env.production
    networks:
      - leadforge-net

networks:
  leadforge-net:
    driver: bridge
